sudo: required

git:
  depth: false
  quiet: true

env:
  - OSG_RELEASE=3.4 OS_VERSION=6 PKG_SET=htcondor-ce
  - OSG_RELEASE=3.4 OS_VERSION=6 PKG_SET=gridftp
  - OSG_RELEASE=3.4 OS_VERSION=7 PKG_SET=htcondor-ce
  - OSG_RELEASE=3.4 OS_VERSION=7 PKG_SET=gridftp
  - OSG_RELEASE=3.4 OS_VERSION=7 PKG_SET=singularity
  - OSG_RELEASE=3.4 OS_VERSION=7 PKG_SET=stashcache
  - OSG_RELEASE=3.4 OS_VERSION=7 PKG_SET=xrootd
  - OSG_RELEASE=3.5 OS_VERSION=7 PKG_SET=htcondor-ce
  - OSG_RELEASE=3.5 OS_VERSION=7 PKG_SET=gridftp
  - OSG_RELEASE=3.5 OS_VERSION=7 PKG_SET=singularity
  - OSG_RELEASE=3.5 OS_VERSION=7 PKG_SET=stashcache
  - OSG_RELEASE=3.5 OS_VERSION=7 PKG_SET=xrootd
  - OSG_RELEASE=3.5 OS_VERSION=8 PKG_SET=singularity
  - OSG_RELEASE=3.5 OS_VERSION=8 PKG_SET=stashcache
  - OSG_RELEASE=3.5 OS_VERSION=8 PKG_SET=xrootd

services:
  - docker

before_install:
  - sudo apt-get update
  - echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s devicemapper"' | sudo tee /etc/default/docker > /dev/null
  - sudo service docker restart
  - sleep 5
  - sudo docker pull centos:centos${OS_VERSION}

script:
 # Run tests in Container
- travis-ci/setup_tests.sh

